# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from algorithms import *
from draw import Draw
import shapefile
 

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimplify = QtWidgets.QMenu(parent=self.menubar)
        self.menuSimplify.setObjectName("menuSimplify")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainForm)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainForm)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(parent=MainForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionMin_Bounding_Rectangle = QtGui.QAction(parent=MainForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/maer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionMin_Bounding_Rectangle.setIcon(icon1)
        self.actionMin_Bounding_Rectangle.setObjectName("actionMin_Bounding_Rectangle")
        self.actionPCAS = QtGui.QAction(parent=MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pca.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPCAS.setIcon(icon2)
        self.actionPCAS.setObjectName("actionPCAS")
        self.actionClear_results = QtGui.QAction(parent=MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/clear_ch.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon3)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_all = QtGui.QAction(parent=MainForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/clear_er.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon4)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionLongest_Edge = QtGui.QAction(parent=MainForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/longestedge.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLongest_Edge.setIcon(icon5)
        self.actionLongest_Edge.setObjectName("actionLongest_Edge")
        self.actionWall_Average = QtGui.QAction(parent=MainForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/wa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWall_Average.setIcon(icon6)
        self.actionWall_Average.setObjectName("actionWall_Average")
        self.actionWeighted_bisector = QtGui.QAction(parent=MainForm)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/weightedbisector.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWeighted_bisector.setIcon(icon7)
        self.actionWeighted_bisector.setObjectName("actionWeighted_bisector")
        self.actionOpen = QtGui.QAction(parent=MainForm)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon8)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSimplify.addAction(self.actionMin_Bounding_Rectangle)
        self.menuSimplify.addAction(self.actionPCAS)
        self.menuSimplify.addAction(self.actionLongest_Edge)
        self.menuSimplify.addAction(self.actionWall_Average)
        self.menuSimplify.addAction(self.actionWeighted_bisector)
        self.menuView.addAction(self.actionClear_results)
        self.menuView.addAction(self.actionClear_all)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimplify.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMin_Bounding_Rectangle)
        self.toolBar.addAction(self.actionPCAS)
        self.toolBar.addAction(self.actionLongest_Edge)
        self.toolBar.addAction(self.actionWall_Average)
        self.toolBar.addAction(self.actionWeighted_bisector)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        
        #Simplify building using MBR
        self.actionMin_Bounding_Rectangle.triggered.connect(self.simplifyBuildingMBRClick)
        self.actionClear_results.triggered.connect(self.clearResultsClick)
        self.actionClear_all.triggered.connect(self.clearAllClick)
        self.actionPCAS.triggered.connect(self.simplifyBuildingPCAClick)
        self.actionWeighted_bisector.triggered.connect(self.simplifyBuildingWBClick)
        self.actionLongest_Edge.triggered.connect(self.simplifyBuildingLongestEdgeClick)
        self.actionWall_Average.triggered.connect(self.simplifyBuildingWallAverageClick)
        # Importing .shp file
        self.actionOpen.triggered.connect(self.openFile)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)
        
   
        
    def simplifyBuildingPCAClick(self):
        #Create objects
        a = Algorithms()

        pols = self.Canvas.getPols()
        total = 0
        correct = 0
        if len(pols) > 0:
            mbr_list = []

            for pol in pols:
                mbr_res = a.simplifyBuildingPCA(pol)
                mbr_list.append(mbr_res)
                
                eval_result = a.ResultsEvaluation(pol, a.sigma)
                total += 1
                if eval_result <= 10:
                    correct += 1
            self.Canvas.setMBRs(mbr_list)
        
        else:
            #Get building
            building = self.Canvas.getBuilding()
            
            #Run simplification
            mbr_res = a.simplifyBuildingPCA(building)
            
            #Return results
            self.Canvas.setMBR(mbr_res)
        
            eval_result = a.ResultsEvaluation(building, a.sigma)
            total += 1
            if eval_result <= 10:
                    correct += 1
        
        self.Canvas.repaint()
        self.showEvaluationResults("PCA", total, correct)
        
    def simplifyBuildingMBRClick(self):
        #Create objects
        a = Algorithms()

        # Loading from .shp
        pols = self.Canvas.getPols()
        total = 0
        correct = 0
        if len(pols) > 0:
            mbr_list = []

            for pol in pols:
                mbr_res = a.simplifyBuildingMBR(pol)
                mbr_list.append(mbr_res)
                
                eval_result = a.ResultsEvaluation(pol, a.sigma)
                total += 1
                if eval_result <= 10:
                    correct += 1
                    
            self.Canvas.setMBRs(mbr_list)

        else:
            #Get building
            building = self.Canvas.getBuilding()
            
            #Run simplification
            mbr_res = a.simplifyBuildingMBR(building)
            
            #Return results
            self.Canvas.setMBR(mbr_res)
        
            eval_result = a.ResultsEvaluation(building, a.sigma)
            total += 1
            if eval_result <= 10:
                    correct += 1
        
        self.Canvas.repaint()
        self.showEvaluationResults("Minimum Bounding Rectangle", total, correct)

    def simplifyBuildingWBClick(self):
        a = Algorithms()

        # Loading from .shp
        pols = self.Canvas.getPols()
        total = 0
        correct = 0
        if len(pols) > 0:
            mbr_list = []

            for pol in pols:
                mbr_res = a.simplifyBuildingWB(pol)
                mbr_list.append(mbr_res)
                
                eval_result = a.ResultsEvaluation(pol, a.sigma)
                total += 1
                if eval_result <= 10:
                    correct += 1
            self.Canvas.setMBRs(mbr_list)

        else:
            #Get building
            building = self.Canvas.getBuilding()
            
            #Run simplification
            mbr_res = a.simplifyBuildingWB(building)
            
            #Return results
            self.Canvas.setMBR(mbr_res)
        
            eval_result = a.ResultsEvaluation(building, a.sigma)
            total += 1
            if eval_result <= 10:
                    correct += 1
        
        self.Canvas.repaint()        
        self.showEvaluationResults("Weighted Bisector", total, correct)        
        
    def simplifyBuildingLongestEdgeClick(self): 
        a = Algorithms()

        #Loading from .shp
        pols = self.Canvas.getPols()
        total = 0
        correct = 0
        #Polygons from shapefile?
        if len(pols) > 0:
            mbr_list = []

            #Process all polygons
            for pol in pols:
                mbr_res = a.simplifyBuildingLongestEdge(pol)
                mbr_list.append(mbr_res)

            #Send results to canvas
                eval_result = a.ResultsEvaluation(pol, a.sigma)
                total += 1
                if eval_result <= 10:
                    correct += 1
            self.Canvas.setMBRs(mbr_list)

        else:
            #Get building
            building = self.Canvas.getBuilding()
            
            #Run method
            mbr_res = a.simplifyBuildingLongestEdge(building)
            
            #Return results
            self.Canvas.setMBR(mbr_res)
        
            eval_result = a.ResultsEvaluation(building, a.sigma)
            total += 1
            if eval_result <= 10:
                correct += 1
        
        self.Canvas.repaint()   
        self.showEvaluationResults("Longest Edge", total, correct)
        
        
    def simplifyBuildingWallAverageClick(self):
        a = Algorithms()
        
        #Loading from .shp
        pols = self.Canvas.getPols()
        total = 0
        correct = 0
        #Polygons from shapefile?
        if len(pols) > 0:
            mbr_list = []

            #Process all polygons
            for pol in pols:
                mbr_res = a.simplifyBuildingWallAverage(pol)
                mbr_list.append(mbr_res)
                
                eval_result = a.ResultsEvaluation(pol, a.sigma)
                total += 1
                if eval_result <= 10:
                    correct += 1

            #Send results to canvas
            self.Canvas.setMBRs(mbr_list)

        else:
            #Get building
            building = self.Canvas.getBuilding()
            
            #Run method
            mbr_res = a.simplifyBuildingWallAverage(building)
            
            #Return results
            self.Canvas.setMBR(mbr_res)
        
            eval_result = a.ResultsEvaluation(building, a.sigma)
            total += 1
            if eval_result <= 10:
                correct += 1
        
        self.Canvas.repaint()
        self.showEvaluationResults("Wall Average", total, correct)
        
        
        

    #General evaluation principle for all methods - AI helped me implement everything because the evaluation wasn't working, so I needed help to create a workflow of evaluation and statistics collection
    #I also created a method showEvaluationResults to display the results in a message box and terminal
    #
    #This block repeats in every method to evaluate cartographic 
    #acceptance and collect data for final statistics
    #
    #eval_result = a.ResultsEvaluation(pol, a.sigma)
    #Calculates average angular deviation from the main direction in degrees
    #
    #total += 1
    #Increments the counter of processed buildings
    #
    #if eval_result <= 10:
    #Checks if deviation meets the 10° cartographic tolerance limit, like in  presentation
    #
    #    correct += 1
    #Counts as a successful generalization for the final success rate

            
            
        
    def clearResultsClick(self):
        #Clear results
        self.Canvas.clearResult()
    
    def clearAllClick(self):
        self.Canvas.clearData()
        
        
    
        
    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Simplify buildings"))
        self.menuFile.setTitle(_translate("MainForm", "File"))
        self.menuSimplify.setTitle(_translate("MainForm", "Simplify"))
        self.menuView.setTitle(_translate("MainForm", "View"))
        self.toolBar.setWindowTitle(_translate("MainForm", "toolBar"))
        self.actionExit.setText(_translate("MainForm", "Exit"))
        self.actionExit.setToolTip(_translate("MainForm", "Close application"))
        self.actionMin_Bounding_Rectangle.setText(_translate("MainForm", "Min. Bounding Rectangle"))
        self.actionMin_Bounding_Rectangle.setToolTip(_translate("MainForm", "Simplify building using minimum bounding rectangle"))
        self.actionPCAS.setText(_translate("MainForm", "PCA"))
        self.actionPCAS.setToolTip(_translate("MainForm", "Simplify building using PCA"))
        self.actionClear_results.setText(_translate("MainForm", "Clear results"))
        self.actionClear_all.setText(_translate("MainForm", "Clear all"))
        self.actionClear_all.setToolTip(_translate("MainForm", "Clear all data"))
        self.actionLongest_Edge.setText(_translate("MainForm", "Longest Edge"))
        self.actionLongest_Edge.setToolTip(_translate("MainForm", "Simplify building using PCA longest edge"))
        self.actionWall_Average.setText(_translate("MainForm", "Wall Average"))
        self.actionWall_Average.setToolTip(_translate("MainForm", "Simplify building using wall average"))
        self.actionWeighted_bisector.setText(_translate("MainForm", "Weighted Bisector"))
        self.actionWeighted_bisector.setToolTip(_translate("MainForm", "Simplify building using weighted bisector"))
        self.actionOpen.setText(_translate("MainForm", "Open"))
        self.actionOpen.setToolTip(_translate("MainForm", "Open file"))


    # LOADING  SHAPEFILE - reused the same from assignment #1
    # AI used here for a correction of syntax and creating workflow/pseudocode of choosing, loading .shp and evaluating the results
   
    def showEvaluationResults(self, method_name, total, correct):
        if total == 0:
            return
            
        #Computing the succes rate
        success_rate = (correct / total) * 100
        
        print(f"METHOD: {method_name}")
        print(f"Total number of simplified buildings: {total}")
        print(f"Successfully simplified (deviation to 10°): {correct}")
        print(f"Total accuracy of the method: {success_rate:.1f} %")
        
            #QMessageBox
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Simplification is finished")
        msg.setText(f"Method: {method_name}\n\nTotal accuracy: {success_rate:.1f} %\n\nMore details are shown in the terminal of VSCode.") #AI helped me to create this message box with the results of evaluation
        msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
        msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        msg.exec()
   
   
   
   
   
    def openFile(self):
        # Pop-up window for searching the shp 
        file_shp, _ = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, "Open .shp", "", "")
        
        # Then loading .shp
        if file_shp:
            self.loadShapefile(file_shp)

    def loadShapefile(self, file_path):
        # Loading .shp from library
        sf = shapefile.Reader(file_path)
        shapes = sf.shapes()

        # Define initializating value of Min-Max Box of our .shp
        min_x = float('inf')
        max_x = float('-inf')
        min_y = float('inf')
        max_y = float('-inf')
        
        # Determine the min and max points 
        for shape in shapes:
            for point in shape.points:
                if point[0] < min_x: 
                    min_x = point[0]
                if point[0] > max_x: 
                    max_x = point[0]
                if point[1] < min_y: 
                    min_y = point[1]
                if point[1] > max_y: 
                    max_y = point[1]

        print(min_x, max_x, min_y, max_y)
        # Calculating a scale so it fits to the canvas window
        zoom = 600/ max(max_x - min_x, max_y - min_y)

        # Clear canvas
        self.Canvas.clearResult()

        # Create a list of polygons
        list_pols = []


        # Scaling all points in the .shp and creating a polygon
        # +100 sets the new coordinates to left and down so the polygon has stable position
        for shape in shapes:
            pol = QtGui.QPolygonF()
            for point in shape.points:
                x = (point[0] - min_x) * zoom + 50
                y = (max_y - point[1] ) * zoom + 50
            
                pol.append(QtCore.QPointF(x, y))
            list_pols.append(pol)
        self.Canvas.setPols(list_pols)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QMainWindow()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec())
